# Generated by Django 5.0.1 on 2024-02-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'CARD'), ('account', 'ACCOUNT')], max_length=10)),
                ('source_type', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], max_length=10)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('limit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('awaiting', 'AWAITING'), ('canceled', 'CANCELED'), ('paid', 'PAID')], max_length=10)),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.requisites')),
            ],
        ),
    ]
